#include "bios_chip.h"

extern const char* g_biosPath;

biosChip::biosChip() {
	std::ifstream file(g_biosPath, std::ios::binary);

	if (!file.is_open())
		throw std::runtime_error("failed to open BIOS\n");

	file.read((char*)biosData, BIOS_SIZE);

	A.resize(0xb6);
	A = {
		{"A(00h) or B(32h) FileOpen(filename,accessmode)"},
		{"A(01h) or B(33h) FileSeek(fd,offset,seektype)"},
		{"A(02h) or B(34h) FileRead(fd,dst,length)"},
		{"A(03h) or B(35h) FileWrite(fd,src,length)"},
		{"A(04h) or B(36h) FileClose(fd)"},
		{"A(05h) or B(37h) FileIoctl(fd,cmd,arg)"},
		{"A(06h) or B(38h) exit(exitcode)"},
		{"A(07h) or B(39h) FileGetDeviceFlag(fd)"},
		{"A(08h) or B(3Ah) FileGetc(fd)"},
		{"A(09h) or B(3Bh) FilePutc(char,fd)"},
		{"A(0Ah) todigit(char)"},
		{"A(0Bh) atof(src); Does NOT work - uses(ABSENT) cop1 !!!"},
		{"A(0Ch) strtoul(src,src_end,base)"},
		{"A(0Dh) strtol(src,src_end,base)"},
		{"A(0Eh) abs(val)"},
		{"A(0Fh) labs(val)"},
		{"A(10h) atoi(src)"},
		{"A(11h) atol(src)"},
		{"A(12h) atob(src,num_dst)"},
		{"A(13h) SaveState(buf)"},
		{"A(14h) RestoreState(buf,param)"},
		{"A(15h) strcat(dst,src)"},
		{"A(16h) strncat(dst,src,maxlen)"},
		{"A(17h) strcmp(str1,str2)"},
		{"A(18h) strncmp(str1,str2,maxlen)"},
		{"A(19h) strcpy(dst,src)"},
		{"A(1Ah) strncpy(dst,src,maxlen)"},
		{"A(1Bh) strlen(src)"},
		{"A(1Ch) index(src,char)"},
		{"A(1Dh) rindex(src,char)"},
		{"A(1Eh) strchr(src,char); exactly the same as 'index'"},
		{"A(1Fh) strrchr(src,char); exactly the same as 'rindex'"},
		{"A(20h) strpbrk(src,list)"},
		{"A(21h) strspn(src,list)"},
		{"A(22h) strcspn(src,list)"},
		{"A(23h) strtok(src,list); use strtok(0,list) in further calls"},
		{"A(24h) strstr(str,substr) - buggy"},
		{"A(25h) toupper(char)"},
		{"A(26h) tolower(char)"},
		{"A(27h) bcopy(src,dst,len)"},
		{"A(28h) bzero(dst,len)"},
		{"A(29h) bcmp(ptr1,ptr2,len); Bugged"},
		{"A(2Ah) memcpy(dst,src,len)"},
		{"A(2Bh) memset(dst,fillbyte,len)"},
		{"A(2Ch) memmove(dst,src,len); Bugged"},
		{"A(2Dh) memcmp(src1,src2,len); Bugged"},
		{"A(2Eh) memchr(src,scanbyte,len)"},
		{"A(2Fh) rand()"},
		{"A(30h) srand(seed)"},
		{"A(31h) qsort(base,nel,width,callback)"},
		{"A(32h) strtod(src,src_end); Does NOT work - uses(ABSENT) cop1 !!!"},
		{"A(33h) malloc(size)"},
		{"A(34h) free(buf)"},
		{"A(35h) lsearch(key,base,nel,width,callback)"},
		{"A(36h) bsearch(key,base,nel,width,callback)"},
		{"A(37h) calloc(sizx,sizy); SLOW!"},
		{"A(38h) realloc(old_buf,new_siz); SLOW!"},
		{"A(39h) InitHeap(addr,size)"},
		{"A(3Ah) SystemErrorExit(exitcode)"},
		{"A(3Bh) or B(3Ch) std_in_getchar()"},
		{"A(3Ch) or B(3Dh) std_out_putchar(char)"},
		{"A(3Dh) or B(3Eh) std_in_gets(dst)"},
		{"A(3Eh) or B(3Fh) std_out_puts(src)"},
		{"A(3Fh) printf(txt,param1,param2,etc.)"},
		{"A(40h) SystemErrorUnresolvedException()"},
		{"A(41h) LoadExeHeader(filename,headerbuf)"},
		{"A(42h) LoadExeFile(filename,headerbuf)"},
		{"A(43h) DoExecute(headerbuf,param1,param2)"},
		{"A(44h) FlushCache()"},
		{"A(45h) init_a0_b0_c0_vectors"},
		{"A(46h) GPU_dw(Xdst,Ydst,Xsiz,Ysiz,src)"},
		{"A(47h) gpu_send_dma(Xdst,Ydst,Xsiz,Ysiz,src)"},
		{"A(48h) SendGP1Command(gp1cmd)"},
		{"A(49h) GPU_cw(gp0cmd); send GP0 command word"},
		{"A(4Ah) GPU_cwp(src,num); send GP0 command wordand parameter words"},
		{"A(4Bh) send_gpu_linked_list(src)"},
		{"A(4Ch) gpu_abort_dma()"},
		{"A(4Dh) GetGPUStatus()"},
		{"A(4Eh) gpu_sync()"},
		{"A(4Fh) SystemError"},
		{"A(50h) SystemError"},
		{"A(51h) LoadAndExecute(filename,stackbase,stackoffset)"},
		{"A(52h) SystemError----OR---- 'GetSysSp()' ? "},
		{"A(53h) SystemError; PS2: set_ioabort_handler(src)"},
		{"A(54h) or A(71h) CdInit()"},
		{"A(55h) or A(70h) _bu_init()"},
		{"A(56h) or A(72h) CdRemove(); does NOT work due to SysDeqIntRP bug"},
		{"A(57h) return 0"},
		{"A(58h) return 0"},
		{"A(59h) return 0"},
		{"A(5Ah) return 0"},
		{"A(5Bh) dev_tty_init(); PS2: SystemError"},
		{"A(5Ch) dev_tty_open(fcb,and unused:'path/name',accessmode); PS2: SystemError"},
		{"A(5Dh) dev_tty_in_out(fcb,cmd); PS2: SystemError"},
		{"A(5Eh) dev_tty_ioctl(fcb,cmd,arg); PS2: SystemError"},
		{"A(5Fh) dev_cd_open(fcb,'path/name',accessmode)"},
		{"A(60h) dev_cd_read(fcb,dst,len)"},
		{"A(61h) dev_cd_close(fcb)"},
		{"A(62h) dev_cd_firstfile(fcb,'path/name',direntry)"},
		{"A(63h) dev_cd_nextfile(fcb,direntry)"},
		{"A(64h) dev_cd_chdir(fcb,'pat')"},
		{"A(65h) dev_card_open(fcb,'path/name',accessmode)"},
		{"A(66h) dev_card_read(fcb,dst,len)"},
		{"A(67h) dev_card_write(fcb,src,len)"},
		{"A(68h) dev_card_close(fcb)"},
		{"A(69h) dev_card_firstfile(fcb,'path/name',direntry)"},
		{"A(6Ah) dev_card_nextfile(fcb,direntry)"},
		{"A(6Bh) dev_card_erase(fcb,'path/name')"},
		{"A(6Ch) dev_card_undelete(fcb,'path/name')"},
		{"A(6Dh) dev_card_format(fcb)"},
		{"A(6Eh) dev_card_rename(fcb1,'path/name1',fcb2,'path/name2')"},
		{"A(6Fh) ? ; card; [r4 + 18h] = 00000000h; card_clear_error(fcb) or so"},
		{"A(70h) or A(55h) _bu_init()"},
		{"A(71h) or A(54h) CdInit()"},
		{"A(72h) or A(56h) CdRemove(); does NOT work due to SysDeqIntRP bug"},
		{"A(73h) return 0"},
		{"A(74h) return 0"},
		{"A(75h) return 0"},
		{"A(76h) return 0"},
		{"A(77h) return 0"},
		{"A(78h) CdAsyncSeekL(src)"},
		{"A(79h) return 0; DTL - H: Unknown ?"},
		{"A(7Ah) return 0; DTL - H: Unknown ?"},
		{"A(7Bh) return 0; DTL - H: Unknown ?"},
		{"A(7Ch) CdAsyncGetStatus(dst)"},
		{"A(7Dh) return 0; DTL - H: Unknown ?"},
		{"A(7Eh) CdAsyncReadSector(count,dst,mode)"},
		{"A(7Fh) return 0; DTL - H: Unknown ?"},
		{"A(80h) return 0; DTL - H: Unknown ?"},
		{"A(81h) CdAsyncSetMode(mode)"},
		{"A(82h) return 0; DTL - H: Unknown ?"},
		{"A(83h) return 0; DTL - H: Unknown ?"},
		{"A(84h) return 0; DTL - H: Unknown ?"},
		{"A(85h) return 0; DTL - H: Unknown ? , or reportedly, CdStop(? )"},
		{"A(86h) return 0; DTL - H: Unknown ?"},
		{"A(87h) return 0; DTL - H: Unknown ?"},
		{"A(88h) return 0; DTL - H: Unknown ?"},
		{"A(89h) return 0; DTL - H: Unknown ?"},
		{"A(8Ah) return 0; DTL - H: Unknown ?"},
		{"A(8Bh) return 0; DTL - H: Unknown ?"},
		{"A(8Ch) return 0; DTL - H: Unknown ?"},
		{"A(8Dh) return 0; DTL - H: Unknown ?"},
		{"A(8Eh) return 0; DTL - H: Unknown ?"},
		{"A(8Fh) return 0; DTL - H: Unknown ?"},
		{"A(90h) CdromIoIrqFunc1()"},
		{"A(91h) CdromDmaIrqFunc1()"},
		{"A(92h) CdromIoIrqFunc2()"},
		{"A(93h) CdromDmaIrqFunc2()"},
		{"A(94h) CdromGetInt5errCode(dst1,dst2)"},
		{"A(95h) CdInitSubFunc()"},
		{"A(96h) AddCDROMDevice()"},
		{"A(97h) AddMemCardDevice(); DTL - H: SystemError"},
		{"A(98h) AddDuartTtyDevice(); DTL - H: AddAdconsTtyDevice; PS2: SystemError"},
		{"A(99h) AddDummyTtyDevice()"},
		{"A(9Ah) SystemError; DTL - H: AddMessageWindowDevice"},
		{"A(9Bh) SystemError; DTL - H: AddCdromSimDevice"},
		{"A(9Ch) SetConf(num_EvCB,num_TCB,stacktop)"},
		{"A(9Dh) GetConf(num_EvCB_dst,num_TCB_dst,stacktop_dst)"},
		{"A(9Eh) SetCdromIrqAutoAbort(type,flag)"},
		{"A(9Fh) SetMemSize(megabytes)"},
		//Below functions A(A0h..B4h) not supported on pre - retail DTL - H2000 devboard :
				{"A(A0h) WarmBoot()"},
				{"A(A1h) SystemErrorBootOrDiskFailure(type,errorcode)"},
				{"A(A2h) EnqueueCdIntr(); with prio = 0 (fixed)"},
				{"A(A3h) DequeueCdIntr(); does NOT work due to SysDeqIntRP bug"},
				{"A(A4h) CdGetLbn(filename); get 1st sector number(or garbage when not found)"},
				{"A(A5h) CdReadSector(count,sector,buffer)"},
				{"A(A6h) CdGetStatus()"},
				{"A(A7h) bu_callback_okay()"},
				{"A(A8h) bu_callback_err_write()"},
				{"A(A9h) bu_callback_err_busy()"},
				{"A(AAh) bu_callback_err_eject()"},
				{"A(ABh) _card_info(port)"},
				{"A(ACh) _card_async_load_directory(port)"},
				{"A(ADh) set_card_auto_format(flag)"},
				{"A(AEh) bu_callback_err_prev_write()"},
				{"A(AFh) card_write_test(port); CEX - 1000: jump_to_00000000h"},
				{"A(B0h) return 0; CEX - 1000: jump_to_00000000h"},
				{"A(B1h) return 0; CEX - 1000: jump_to_00000000h"},
				{"A(B2h) ioabort_raw(param); CEX - 1000: jump_to_00000000h"},
				{"A(B3h) return 0; CEX - 1000: jump_to_00000000h"},
				{"A(B4h) GetSystemInfo(index); CEX - 1000: jump_to_00000000h" },
				{"A(B5h..BFh) N / A; jump_to_00000000h" },
	};

	B.resize(0x60);
	B = {
		{"B(00h) alloc_kernel_memory(size)"},
		{"B(01h) free_kernel_memory(buf)"},
		{"B(02h) init_timer(t, reload, flags)"},
		{"B(03h) get_timer(t)"},
		{"B(04h) enable_timer_irq(t)"},
		{"B(05h) disable_timer_irq(t)"},
		{"B(06h) restart_timer(t)"},
		{"B(07h) DeliverEvent(class, spec)"},
		{"B(08h) OpenEvent(class, spec, mode, func)"},
		{"B(09h) CloseEvent(event)"},
		{"B(0Ah) WaitEvent(event)"},
		{"B(0Bh) TestEvent(event)"},
		{"B(0Ch) EnableEvent(event)"},
		{"B(0Dh) DisableEvent(event)"},
		{"B(0Eh) OpenThread(reg_PC, reg_SP_FP, reg_GP)"},
		{"B(0Fh) CloseThread(handle)"},
		{"B(10h) ChangeThread(handle)"},
		{"B(11h) jump_to_00000000h"},
		{"B(12h) InitPad(buf1, siz1, buf2, siz2)"},
		{"B(13h) StartPad()"},
		{"B(14h) StopPad()"},
		{"B(15h) OutdatedPadInitAndStart(type, button_dest, unused, unused)"},
		{"B(16h) OutdatedPadGetButtons()"},
		{"B(17h) ReturnFromException()"},
		{"B(18h) SetDefaultExitFromException()"},
		{"B(19h) SetCustomExitFromException(addr)"},
		{"B(1Ah) SystemError; PS2: return 0"},
		{"B(1Bh) SystemError; PS2: return 0"},
		{"B(1Ch) SystemError; PS2: return 0"},
		{"B(1Dh) SystemError; PS2: return 0"},
		{"B(1Eh) SystemError; PS2: return 0"},
		{"B(1Fh) SystemError; PS2: return 0"},
		{"B(20h) UnDeliverEvent(class, spec)"},
		{"B(21h) SystemError; PS2: return 0"},
		{"B(22h) SystemError; PS2: return 0"},
		{"B(23h) SystemError; PS2: return 0"},
		{"B(24h) jump_to_00000000h"},
		{"B(25h) jump_to_00000000h"},
		{"B(26h) jump_to_00000000h"},
		{"B(27h) jump_to_00000000h"},
		{"B(28h) jump_to_00000000h"},
		{"B(29h) jump_to_00000000h"},
		{"B(2Ah) SystemError; PS2: return 0"},
		{"B(2Bh) SystemError; PS2: return 0"},
		{"B(2Ch) jump_to_00000000h"},
		{"B(2Dh) jump_to_00000000h"},
		{"B(2Eh) jump_to_00000000h"},
		{"B(2Fh) jump_to_00000000h"},
		{"B(30h) jump_to_00000000h"},
		{"B(31h) jump_to_00000000h"},
		{"B(32h) or A(00h) FileOpen(filename, accessmode)"},
		{"B(33h) or A(01h) FileSeek(fd, offset, seektype)"},
		{"B(34h) or A(02h) FileRead(fd, dst, length)"},
		{"B(35h) or A(03h) FileWrite(fd, src, length)"},
		{"B(36h) or A(04h) FileClose(fd)"},
		{"B(37h) or A(05h) FileIoctl(fd, cmd, arg)"},
		{"B(38h) or A(06h) exit(exitcode)"},
		{"B(39h) or A(07h) FileGetDeviceFlag(fd)"},
		{"B(3Ah) or A(08h) FileGetc(fd)"},
		{"B(3Bh) or A(09h) FilePutc(char, fd)"},
		{"B(3Ch) or A(3Bh) std_in_getchar()"},
		{"B(3Dh) or A(3Ch) std_out_putchar(char)"},
		{"B(3Eh) or A(3Dh) std_in_gets(dst)"},
		{"B(3Fh) or A(3Eh) std_out_puts(src)"},
		{"B(40h) chdir(name)"},
		{"B(41h) FormatDevice(devicename)"},
		{"B(42h) firstfile(filename, direntry)"},
		{"B(43h) nextfile(direntry)"},
		{"B(44h) FileRename(old_filename, new_filename)"},
		{"B(45h) FileDelete(filename)"},
		{"B(46h) FileUndelete(filename)"},
		{"B(47h) AddDevice(device_info); subfunction for AddXxxDevice functions"},
		{"B(48h) RemoveDevice(device_name_lowercase)"},
		{"B(49h) PrintInstalledDevices()"},
		//Below functions B(4Ah..5Dh) not supported on pre-retail DTL-H2000 devboard:
				{"B(4Ah) InitCard(pad_enable); uses / destroys k0 / k1 !!!"},
				{"B(4Bh) StartCard()"},
				{"B(4Ch) StopCard()"},
				{"B(4Dh) _card_info_subfunc(port); subfunction for '_card_info'"},
				{"B(4Eh) write_card_sector(port, sector, src)"},
				{"B(4Fh) read_card_sector(port, sector, dst)"},
				{"B(50h) allow_new_card()"},
				{"B(51h) Krom2RawAdd(shiftjis_code)"},
				{"B(52h) SystemError; PS2: return 0"},
				{"B(53h) Krom2Offset(shiftjis_code)"},
				{"B(54h) GetLastError()"},
				{"B(55h) GetLastFileError(fd)"},
				{"B(56h) GetC0Table"},
				{"B(57h) GetB0Table"},
				{"B(58h) get_bu_callback_port()"},
				{"B(59h) testdevice(devicename)"},
				{"B(5Ah) SystemError; PS2: return 0"},
				{"B(5Bh) ChangeClearPad(int)"},
				{"B(5Ch) get_card_status(slot)"},
				{"B(5Dh) wait_card_status(slot)"},
				{"B(5Eh..FFh) N / A; jump_to_00000000h; CEX - 1000: B(5Eh..F6h) only"},
				{"B(100h....) N / A; garbage; CEX - 1000: B(F7h.....) and up"}
	};

	C.resize(0x20);
	C = {
		{"C(00h) EnqueueTimerAndVblankIrqs(priority); used with prio = 1"},
		{"C(01h) EnqueueSyscallHandler(priority); used with prio = 0"},
		{"C(02h) SysEnqIntRP(priority, struc); bugged, use with care"},
		{"C(03h) SysDeqIntRP(priority, struc); bugged, use with care"},
		{"C(04h) get_free_EvCB_slot()"},
		{"C(05h) get_free_TCB_slot()"},
		{"C(06h) ExceptionHandler()"},
		{"C(07h) InstallExceptionHandlers(); destroys / uses k0 / k1"},
		{"C(08h) SysInitMemory(addr, size)"},
		{"C(09h) SysInitKernelVariables()"},
		{"C(0Ah) ChangeClearRCnt(t, flag)"},
		{"C(0Bh) SystemError; PS2: return 0"},
		{"C(0Ch) InitDefInt(priority); used with prio = 3"},
		{"C(0Dh) SetIrqAutoAck(irq, flag)"},
		{"C(0Eh) return 0; DTL - H2000: dev_sio_init"},
		{"C(0Fh) return 0; DTL - H2000: dev_sio_open"},
		{"C(10h) return 0; DTL - H2000: dev_sio_in_out"},
		{"C(11h) return 0; DTL - H2000: dev_sio_ioctl"},
		{"C(12h) InstallDevices(ttyflag)"},
		{"C(13h) FlushStdInOutPut()"},
		{"C(14h) return 0; DTL - H2000: SystemError"},
		{"C(15h) tty_cdevinput(circ, char)"},
		{"C(16h) tty_cdevscan()"},
		{"C(17h) tty_circgetc(circ); uses r5 as garbage txt for ioabort"},
		{"C(18h) tty_circputc(char, circ)"},
		{"C(19h) ioabort(txt1, txt2)"},
		{"C(1Ah) set_card_find_mode(mode); 0 = normal, 1 = find deleted files"},
		{"C(1Bh) KernelRedirect(ttyflag); PS2: ttyflag = 1 causes SystemError"},
		{"C(1Ch) AdjustA0Table()"},
		{"C(1Dh) get_card_find_mode()"},
		{"C(1Eh..7Fh) N / A; jump_to_00000000h"},
		{"C(80h.....) N / A; mirrors to B(00h.....)"}
	};
}